# -*- python -*-

tools = Split("""
qt4
ascope
qtt_qtconfig
doxygen
fftw
boost_program_options
kadds
""")

env = Environment(tools = ['default'] + tools)

sources = Split("""
main.cpp
AScopeReader.cpp
""")

headers = Split("""
""")

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

kascope = env.Program('kascope', sources)

#Default(kascope, html)
Default(kascope)



