# -*- python -*-

tools = Split("""
qt4
qtt_qtconfig
kadds
doxygen
boost_program_options
rapradar
""")

env = Environment(tools = ['default'] + tools)

qt4modules = ['QtCore', 'QtGui']
env.EnableQt4Modules(qt4modules)

sources = Split("""
kaprod.cpp
ProductGenerator.cpp
""")

headers = Split("""
ProductGenerator.h
""")

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

kaprod = env.Program('kaprod', sources)

Default(kaprod, html)



