# -*- python -*-

tools = Split("""
kadds
qtt_qtconfig
boost_date_time
boost_program_options
""")

env = Environment(tools = ['default'] + tools)

sources = Split("""
main.cpp
SnifferTSReader.cpp
""")

headers = Split("""
SnifferTSReader.h
""")

sniffer = env.Program('sniffer', sources)

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

Default(sniffer, html)

