# -*- python -*-

tools = Split("""
boost_date_time
boost_thread
boost_program_options
doxygen
logx
lrose
Pentek7142
pmc730
qtcore
xmitclient
xmlrpc
""")

sources = Split("""
Adf4001.cpp
BurstData.cpp
KaDrxConfig.cpp
KaDrxPub.cpp
KaMerge.cpp
KaMonitor.cpp
KaOscControl.cpp
KaOscillator3.cpp
KaPmc730.cpp
PulseData.cpp
TtyOscillator.cpp
kadrx.cpp
qrc_kadrx.cc
""")

headers = Split("""
Adf4001.h
BurstData.h
CircBuffer.h
KaDrxConfig.h
KaDrxPub.h
KaMerge.h
KaMonitor.h
KaOscControl.h
KaOscillator3.h
KaPmc730.h
PulseData.h
TtyOscillator.h
""")
# Qt resource file
qrcfiles = Split("""
kadrx.qrc
""")

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore'])

env.Qrc(qrcfiles)

kadrx = env.Program('kadrx', sources)

html = env.Apidocs(sources + headers)

Default(kadrx, html)

