# -*- python -*-

tools = Split("""
kadds
logx
pentek
qtt_qtconfig
boost_date_time
boost_program_options
doxygen
qt4
pmc730
""")

sources = Split("""
Adf4001.cpp
BurstData.cpp
KaAfc.cpp
KaDrxConfig.cpp
KaDrxPub.cpp
KaMerge.cpp
KaOscillator3.cpp
KaPmc730.cpp
PulseData.cpp
TtyOscillator.cpp
main.cpp
""")

headers = Split("""
Adf4001.h
BurstData.h
CircBuffer.h
KaAfc.h
KaDrxConfig.h
KaDrxPub.h
KaMerge.h
KaOscillator3.h
KaPmc730.h
PulseData.h
TtyOscillator.h
""")

env = Environment(tools = ['default'] + tools)

kadrx = env.Program('kadrx', sources)

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

Default(kadrx, html)

