# -*- python -*-

tools = Split("""
pmc730
logx
doxygen
""")

sources = Split("""
Adf4001.cpp
KaOscillator3.cpp
KaAfc.cpp
""")

headers = Split("""
Adf4001.h
KaOscillator3.h
""")

env = Environment(tools = ['default'] + tools)

kaafc = env.Program('kaafc', sources)

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

Default(kaafc, html)

